[package]
name = "json-struct"
version = "0.1.2"
authors = ["Mathieu Lemay <acidrain1@gmail.com>"]
edition = "2018"

[dependencies]
clap = "^2.33"
serde_json = "^1.0"
serde_yaml = "^0.8"
termcolor = "^1.1"
atty = "^0.2"
