name: Tests

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["*"]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint
        run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings

      - name: Run tests
        run: cargo test --verbose
